#!/usr/bin/env bash
# Transfers a file to a remote server

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

scp -o StrictHostKeyChecking=no -i "${SSH_KEY_PATH}" "${FILE_PATH}" "${USERNAME}@${SERVER_IP}:~/"
