#!/usr/bin/env bash
# Installs Nginx and configures a custom HTML page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
