#!/usr/bin/env bash
# This script configures a custom 404 page for Nginx

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

service nginx restart
