#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page and a specific redirection
apt-get update
apt-get install -y nginx
service nginx start
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF
service nginx restart
