#!/usr/bin/env bash
# This script configures an Nginx server with a custom header 'X-Served-By'
set -e

# Update apt repositories
apt-get update

# Install Nginx 
apt-get install -y nginx

# Create index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add server redirect rule  
sed -i '/server_name _;/a \\trewrite ^\/redirect_me https:\/\/github.com\/mansouriyassine permanent;' /etc/nginx/sites-available/default  

# Set up custom 404 error page
sed -i '/server_name _;/a \\terror_page 404 \/custom_404.html;' /etc/nginx/sites-available/default

# Create location block for custom 404 page  
sed -i '/error_page 404 \/custom_404.html;/a \\tlocation = \/custom_404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}' /etc/nginx/sites-available/default

# Add custom X-Served-By header
sed -i '/http {/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf  

# Check Nginx config
nginx -t 

# Restart Nginx to apply changes  
systemctl restart nginx
