#!/usr/bin/env bash
# This script installs and configures HAProxy to load balance traffic between two web servers

# Exit script on any error
set -e

# Update the package list
apt update 

# Install HAProxy
apt install -y haproxy

# Optional: Install socat for HAProxy testing
apt install -y socat

# Enable HAProxy to start on system boot
echo "ENABLED=1" > /etc/default/haproxy

# Create a new HAProxy configuration file with the following settings
cat <<EOF > /etc/haproxy/haproxy.cfg
# Global settings
global
    log /dev/log local0 info
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Default settings for all 'listen' and 'backend' sections
defaults
    mode http
    log global
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

# Frontend configuration
frontend http-in
    bind *:80 
    stats enable
    stats uri /haproxy?stats
    default_backend webservers

# Backend configuration for load balancing
backend webservers
    balance roundrobin
    option forwardfor
    server web1 3.90.85.41:80 check
    server web2 54.174.187.4:80 check    
EOF

# Validate HAProxy configuration file for any syntax errors
haproxy -f /etc/haproxy/haproxy.cfg -c

# Restart HAProxy to apply the new configuration
systemctl restart haproxy
