#!/usr/bin/env bash
# This is for task 1. script installs and sets up HAProxy as a load balancer

# Update system pakcage list and install software properties tools
apt-get update -y
apt-get install -y software-properties-common

# Add the official HAProxy PPA to the system
add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update the package list with the new PPA and install HAProxy
apt-get update -y
apt-get install -y haproxy=1.8.\*

# Configure HAProxy and start on boot
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy in order to distribute traffic between the web servers
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 441617-web-01 3.90.85.41:80 check
   server 441617-web-02 54.174.187.4:80 check
EOF

# Restart HAProxy and apply configuration
service haproxy restart
