#!/usr/bin/env bash
# This script initiates an SSH connection to Web-02 for quick access.

# Start the ssh-agent in the background.
eval "$(ssh-agent -s)"

# Add your SSH private key to the ssh-agent.
ssh-add ~/.ssh/school

# Connect to the Web-02 server using its IP address.
ssh ubuntu@54.174.187.4
