#!/usr/bin/env bash
# Configure Nginx to listen on port 80 for all active IPv4 IPs
apt-get update && apt-get install -y nginx && service nginx start
sed -i 's/^.*listen \[::\]:80 .*$/    listen 80 default_server;\n    listen [::]:80 default_server;/' /etc/nginx/sites-available/default
service nginx restart
