#!/usr/bin/env bash
# Configure Nginx to listen on port 80 for all active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
