#!/usr/bin/env bash
# Short script to install then configure Nginx to listen on port 80 task 0
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
