#!/usr/bin/env bash
apt update;apt install -y nginx
sed -i 's/80 default_server/80 default_server\n    listen [::]:80 default_server/' /etc/nginx/sites-available/default  
nginx -s reload  
curl 127.0.0.1
nginx -t && nginx -s stop
