#!/bin/bash
# Create the PID file
echo $$ > /var/run/myscript.pid


cleanup() {
    echo "Cleaning up and exiting"
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'cleanup' SIGTERM SIGQUIT
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

echo "To infinity and beyond"

while true; do
    sleep 1
done
