#!/usr/bin/env bash
# Manage my process

SCRIPT_PATH="/path/to/manage_my_process"

start() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process is already running."
        return 1
    fi

    $SCRIPT_PATH &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop() {
    if [ -f /var/run/my_process.pid ]; then
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
