#!/usr/bin/env bash
# This script kills the 7-highlander process.
pid=$(pgrep -f '7-highlander')

if [ -n "$pid" ]; then
    # If the PID is found, send a SIGTERM signal to terminate the process.
    kill -15 "$pid"
else
    echo "7-highlander process not found."
fi
