#!/usr/bin/env bash

# This Bash script reads the /etc/passwd file and displays user information in a storytelling format.

while IFS=: read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd
