#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59.

hour=0

while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  for minute in {1..59}; do
    echo $minute
  done
  hour=$((hour+1))
done
