#!/usr/bin/env bash
# Displays directory contents in a list format with names after the first dash.

for item in *; do
  if [[ -d "$item" && ! "$item" = .* ]]; then
    name="${item#*-}"
    echo "$name"
  fi
done
