#!/usr/bin/env bash
# Display directory contents in a list format, showing only the part of the name after the first dash.

for item in *
do
    extracted_name=$(echo "$item" | cut -d'-' -f2)
    echo "$extracted_name"
done
