#!/usr/bin/env bash
# Configure IP addresses for localhost and Facebook

new_localhost_ip="127.0.0.2"
new_facebook_ip="8.8.8.8"

if [ -f /.dockerenv ]; then
    echo "Running inside a Docker container. Make sure to modify the host file directly."
    exit 1
fi

hosts_file="/etc/hosts"
cp "$hosts_file" "$hosts_file.backup"

sed -i "s/127.0.0.1/$new_localhost_ip/g" "$hosts_file"

echo "$new_facebook_ip facebook.com" >> "$hosts_file"

echo "IP addresses updated successfully!"
