#!/usr/bin/env bash
# This script is intended to fix the web server and serve a specific page
which apache2 >/dev/null || (apt-get update && apt-get install -y apache2)
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
chown -R www-data:www-data /var/www/html/
chmod -R 755 /var/www/html/
service apache2 restart
