#!/usr/bin/env bash
# This script is intended to fix the web server and serve a specific page
if ! which apache2 > /dev/null; then
    apt-get update && apt-get install -y apache2
fi

service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
sed -i 's/Listen 80/Listen 0.0.0.0:80/' /etc/apache2/ports.conf
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
a2enmod rewrite
service apache2 restart

if curl -s localhost | grep -q "Hello Holberton"; then
    echo "Content check passed"
else
    echo "Content check failed"
    exit 1
fi
