#!/usr/bin/env bash
# Reloads Gunicorn gracefully

# Retrieve the PID of the master Gunicorn process
master_pid=$(pgrep -f 'gunicorn: master')

# Retrieve the current number of workers
current_workers=$(pgrep -c -f 'gunicorn: worker')

echo "Master PID: $master_pid"
echo "$current_workers"
echo "Current number of workers:"
echo "$current_workers"

# Restart Gunicorn
echo "Restarting Gunicorn..."
kill -HUP "$master_pid"

# Wait for the new workers to be spawned
sleep 2

# Retrieve the new number of workers
new_workers=$(pgrep -c -f 'gunicorn: worker')

echo "New number of workers after restart:"
echo "$new_workers"
