#!/usr/bin/env bash
# This script creates an RSA key pair with a name 'school' and protected by the passphrase 'betty'

# Create an RSA key pair with 4096 bits named 'school'
ssh-keygen -t rsa -b 4096 -C "school" -f school -N "betty"
